version: '3.8'

services:
  nutrition-api:
    container_name: nutrition-api
    image: ghcr.io/kuya-carlo/nutrition-api:v1.3
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=supersecretkey
      - ALGORITHM=HS256
      - DATABASE_URL=sqlite:////data/database.db
      - ALEMBIC_DB_URL=sqlite:////data/database.db
    volumes:
      - nutrition_db:/data:rw

volumes:
  nutrition_db: